# Generated by Django 5.2 on 2025-04-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=69)),
                ('price', models.DecimalField(decimal_places=6, max_digits=6)),
                ('description', models.CharField(max_length=150)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
