# Generated by Django 5.2 on 2025-04-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('buy_product', 'cat_buy_product')]},
        ),
    ]
