# Generated by Django 5.2 on 2025-04-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('buy_product', 'can buy product')]},
        ),
    ]
