# Generated by Django 5.2 on 2025-04-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimony", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimony",
            old_name="testimoni_id",
            new_name="testimony_id",
        ),
    ]
