# Generated by Django 5.2 on 2025-04-04 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('nomor_hp', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('nomor_hp', models.CharField(max_length=16)),
                ('domicile', models.CharField(choices=[('jakut', 'Jakarta Utara'), ('jakbar', 'Jakarta Barat'), ('jaktim', 'Jakarta Timur'), ('jakpus', 'Jakarta Pusat'), ('jaksel', 'Jakarta Selatan'), ('depok', 'Depok'), ('bekasi_kota', 'Bekasi (Kota)'), ('bekasi_kab', 'Bekasi (Kabupaten)'), ('bogor_kota', 'Bogor (Kota)'), ('bogor_kab', 'Bogor (Kabupaten)'), ('tangsel', 'Tangerang Selatan'), ('tangerang_kota', 'Tangerang (Kota)'), ('tangerang_kab', 'Tangerang (Kabupaten)')], default='Domisili kamu dimana', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('nomor_hp', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=50)),
                ('domicile', models.CharField(choices=[('jakut', 'Jakarta Utara'), ('jakbar', 'Jakarta Barat'), ('jaktim', 'Jakarta Timur'), ('jakpus', 'Jakarta Pusat'), ('jaksel', 'Jakarta Selatan'), ('depok', 'Depok'), ('bekasi_kota', 'Bekasi (Kota)'), ('bekasi_kab', 'Bekasi (Kabupaten)'), ('bogor_kota', 'Bogor (Kota)'), ('bogor_kab', 'Bogor (Kabupaten)'), ('tangsel', 'Tangerang Selatan'), ('tangerang_kota', 'Tangerang (Kota)'), ('tangerang_kab', 'Tangerang (Kabupaten)')], default='Domisili kamu dimana', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
