# Generated by Django 5.2 on 2025-04-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaccount',
            name='last_attempt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='walletaccount',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WalletSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField()),
                ('walletAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.walletaccount')),
            ],
        ),
    ]
