# Generated by Django 5.2 on 2025-04-09 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletaccount_last_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
