# Generated by Django 5.2 on 2025-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_orderpayment_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=12),
        ),
    ]
