# Generated by Django 5.2 on 2025-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_checked_out_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': [('can_checkout_cart', 'checkout_cart')]},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
