# Generated by Django 5.2 on 2025-04-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': [('checkout_cart', 'can_checkout_cart')]},
        ),
    ]
