# Generated by Django 5.2 on 2025-04-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'permissions': [('checkout_cart', 'Can checkout cart')]},
        ),
    ]
