# Generated by Django 5.2 on 2025-04-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('set to paid', 'can set to paid'), ('set to prepared', 'can set to prepared'), ('set to ready', 'can set to ready'), ('set to delivered', 'can set to delivered'), ('set to completed', 'can set to completed'), ('set to cancelled', 'can set to cancelled'), ('set to reviewed', 'can set to reviewed')]},
        ),
    ]
