# Generated by Django 5.2 on 2025-04-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('set_to_paid', 'can set to paid'), ('set_to_prepared', 'can set to prepared'), ('set_to_ready', 'can set to ready'), ('set_to_delivered', 'can set to delivered'), ('set_to_completed', 'can set to completed'), ('set_to_cancelled', 'can set to cancelled'), ('set_to_reviewed', 'can set to reviewed')]},
        ),
    ]
